In [4]:
import numpy as np # linear algebra

In [10]:
# 2D Array Rotation based on ariticle: https://stackoverflow.com/questions/19878280/efficient-way-to-shift-2d-matrices-in-both-directions/25628221 

X = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])

XR = np.roll(X, 1, axis=1) # right one

print("init array")
print(X)
print("rotated array")
print(XR)

init array
[[0 1 2]
 [3 4 5]
 [6 7 8]]
rotated array
[[2 0 1]
 [5 3 4]
 [8 6 7]]


In [20]:
import collections 

X = collections.deque([1, 2, 3, 4, 5])

X.rotate(1)
XR = np.array(X)
print(XR)

X.rotate(-2)
XR = np.array(X)
print(XR)

[5 1 2 3 4]
[2 3 4 5 1]
